//! Conversation State Machine and Barge-In Handler (P0-B & P0-C).
//!
//! Manages real-time interaction states and enforces strict state transitions:
//! IDLE <-> LISTENING <-> THINKING <-> SPEAKING <-> INTERRUPTED / AWAITING_CONTINUATION.
//!
//! When interrupted, the state machine calculates the exact `heard_text` that was emitted
//! before interruption, trimming unspoken words so the conversational history is never polluted.

use serde::{Deserialize, Serialize};

/// High-level interaction state of the character.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationState {
    /// Character is quiet, awaiting user voice, chat, or autonomous action.
    Idle,

    /// Microphone or VAD has detected user speech; audio buffer is accumulating.
    Listening { started_at: u64 },

    /// User utterance complete; LLM Brain is deliberating & generating token stream.
    Thinking { started_at: u64, user_input: String },

    /// Character is actively vocalizing via TTS and avatar is lip-syncing.
    Speaking {
        started_at: u64,
        utterance_id: String,
        full_text: String,
        heard_text: String,
    },

    /// User interrupted character mid-speech; speech was cut off.
    Interrupted {
        interrupted_at: u64,
        heard_text: String,
        unspoken_text: String,
    },

    /// Character replied with a short acknowledgement ("Dạ?") and is awaiting the full prompt.
    AwaitingContinuation {
        started_at: u64,
        prompt_ack: String,
        expires_at: u64,
    },

    /// An unexpected runtime failure occurred; recovering back to Idle.
    Error { occurred_at: u64, error: String },
}

impl ConversationState {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Idle => "Idle",
            Self::Listening { .. } => "Listening",
            Self::Thinking { .. } => "Thinking",
            Self::Speaking { .. } => "Speaking",
            Self::Interrupted { .. } => "Interrupted",
            Self::AwaitingContinuation { .. } => "AwaitingContinuation",
            Self::Error { .. } => "Error",
        }
    }

    pub fn is_idle(&self) -> bool {
        matches!(self, Self::Idle)
    }

    pub fn is_speaking(&self) -> bool {
        matches!(self, Self::Speaking { .. })
    }

    pub fn is_thinking(&self) -> bool {
        matches!(self, Self::Thinking { .. })
    }

    pub fn is_listening(&self) -> bool {
        matches!(self, Self::Listening { .. })
    }
}

/// Domain error returned on invalid state machine transitions.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum TransitionError {
    #[error("Invalid transition from {from} to {to}: {reason}")]
    InvalidTransition {
        from: &'static str,
        to: &'static str,
        reason: String,
    },
}

/// Typed events emitted by the conversation state machine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationEvent {
    StateChanged {
        from: String,
        to: String,
        timestamp: u64,
    },
    UserSpeechStarted {
        timestamp: u64,
    },
    ThinkingStarted {
        user_input: String,
        timestamp: u64,
    },
    SpeakingStarted {
        utterance_id: String,
        text: String,
        timestamp: u64,
    },
    SpeechInterrupted {
        utterance_id: String,
        heard_text: String,
        unspoken_text: String,
        preserved_history: String,
        timestamp: u64,
    },
    SpeechCompleted {
        utterance_id: String,
        full_text: String,
        timestamp: u64,
    },
    ContinuationRequested {
        ack: String,
        expires_at: u64,
    },
    ContinuationExpired {
        timestamp: u64,
    },
}

/// Outcome of a Barge-In interruption.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InterruptionResult {
    /// What the user actually heard before speaking over the character.
    pub heard_text: String,

    /// Text that was generated by LLM but never reached the speaker.
    pub unspoken_text: String,

    /// Sanitized string for dialogue history: e.g. "Chào bạn [Interrupted by user]".
    pub preserved_history_text: String,

    /// Timestamp of interruption.
    pub timestamp: u64,
}

/// Formal Conversation State Machine for VirtualCharacter.
#[derive(Debug, Clone)]
pub struct ConversationStateMachine {
    current_state: ConversationState,
    history: Vec<ConversationEvent>,
}

impl Default for ConversationStateMachine {
    fn default() -> Self {
        Self {
            current_state: ConversationState::Idle,
            history: Vec::new(),
        }
    }
}

impl ConversationStateMachine {
    pub fn new() -> Self {
        Self::default()
    }

    /// Current interaction state.
    pub fn state(&self) -> &ConversationState {
        &self.current_state
    }

    /// Record event in transition history.
    fn record_event(&mut self, event: ConversationEvent) {
        self.history.push(event);
    }

    /// User starts speaking (VAD speech detected or push-to-talk pressed).
    ///
    /// If character is currently Speaking, this automatically triggers a Barge-In interruption!
    pub fn on_user_speech_started(
        &mut self,
        now: u64,
    ) -> Result<Option<InterruptionResult>, TransitionError> {
        let mut interruption = None;

        if self.current_state.is_speaking() {
            // User interrupted while character was speaking!
            interruption = Some(self.interrupt(now, None)?);
        }

        let from = self.current_state.name().to_string();
        self.current_state = ConversationState::Listening { started_at: now };
        let to = self.current_state.name().to_string();

        self.record_event(ConversationEvent::StateChanged {
            from,
            to,
            timestamp: now,
        });
        self.record_event(ConversationEvent::UserSpeechStarted { timestamp: now });

        Ok(interruption)
    }

    /// User transcript finalized; start thinking.
    pub fn on_transcript_final(
        &mut self,
        now: u64,
        user_input: impl Into<String>,
    ) -> Result<ConversationEvent, TransitionError> {
        let input = user_input.into();
        match &self.current_state {
            ConversationState::Listening { .. }
            | ConversationState::Interrupted { .. }
            | ConversationState::AwaitingContinuation { .. }
            | ConversationState::Idle => {
                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Thinking {
                    started_at: now,
                    user_input: input.clone(),
                };
                let to = self.current_state.name().to_string();

                let event = ConversationEvent::ThinkingStarted {
                    user_input: input,
                    timestamp: now,
                };
                self.record_event(ConversationEvent::StateChanged { from, to, timestamp: now });
                self.record_event(event.clone());
                Ok(event)
            }
            _ => Err(TransitionError::InvalidTransition {
                from: self.current_state.name(),
                to: "Thinking",
                reason: "Can only enter Thinking from Listening, Interrupted, Idle, or AwaitingContinuation".into(),
            }),
        }
    }

    /// First sentence audio is ready; start vocalizing.
    pub fn on_first_audio_ready(
        &mut self,
        now: u64,
        utterance_id: impl Into<String>,
        full_text: impl Into<String>,
    ) -> Result<ConversationEvent, TransitionError> {
        let utt_id = utterance_id.into();
        let text = full_text.into();

        match &self.current_state {
            ConversationState::Thinking { .. } | ConversationState::Idle => {
                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Speaking {
                    started_at: now,
                    utterance_id: utt_id.clone(),
                    full_text: text.clone(),
                    heard_text: String::new(),
                };
                let to = self.current_state.name().to_string();

                let event = ConversationEvent::SpeakingStarted {
                    utterance_id: utt_id,
                    text,
                    timestamp: now,
                };
                self.record_event(ConversationEvent::StateChanged {
                    from,
                    to,
                    timestamp: now,
                });
                self.record_event(event.clone());
                Ok(event)
            }
            _ => Err(TransitionError::InvalidTransition {
                from: self.current_state.name(),
                to: "Speaking",
                reason: "Can only enter Speaking from Thinking or Idle".into(),
            }),
        }
    }

    /// Update audio progress as chunks are sent to and played by the audio device.
    pub fn update_heard_progress(&mut self, delta: &str) {
        if let ConversationState::Speaking {
            ref mut heard_text, ..
        } = self.current_state
        {
            if !heard_text.is_empty() && !delta.starts_with(' ') && !heard_text.ends_with(' ') {
                heard_text.push(' ');
            }
            heard_text.push_str(delta);
        }
    }

    /// Interrupt character speech immediately (Barge-In).
    ///
    /// If `explicit_heard` is provided from client audio tracking, it is used;
    /// otherwise it falls back to the current internal `heard_text`.
    pub fn interrupt(
        &mut self,
        now: u64,
        explicit_heard: Option<String>,
    ) -> Result<InterruptionResult, TransitionError> {
        match &self.current_state {
            ConversationState::Speaking {
                utterance_id,
                full_text,
                heard_text,
                ..
            } => {
                let utt_id = utterance_id.clone();
                let full = full_text.clone();
                let actual_heard = explicit_heard.unwrap_or_else(|| heard_text.clone());

                let unspoken = if full.len() > actual_heard.len() {
                    full[actual_heard.len()..].trim().to_string()
                } else {
                    String::new()
                };

                let preserved_history = if actual_heard.trim().is_empty() {
                    "[Interrupted by user]".to_string()
                } else {
                    format!("{} [Interrupted by user]", actual_heard.trim())
                };

                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Interrupted {
                    interrupted_at: now,
                    heard_text: actual_heard.clone(),
                    unspoken_text: unspoken.clone(),
                };
                let to = self.current_state.name().to_string();

                let res = InterruptionResult {
                    heard_text: actual_heard.clone(),
                    unspoken_text: unspoken.clone(),
                    preserved_history_text: preserved_history.clone(),
                    timestamp: now,
                };

                self.record_event(ConversationEvent::StateChanged {
                    from,
                    to,
                    timestamp: now,
                });
                self.record_event(ConversationEvent::SpeechInterrupted {
                    utterance_id: utt_id,
                    heard_text: actual_heard,
                    unspoken_text: unspoken,
                    preserved_history,
                    timestamp: now,
                });

                Ok(res)
            }
            ConversationState::Thinking { .. } => {
                // Interrupted while still thinking (before any audio was generated)
                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Interrupted {
                    interrupted_at: now,
                    heard_text: String::new(),
                    unspoken_text: String::new(),
                };
                let to = self.current_state.name().to_string();

                let res = InterruptionResult {
                    heard_text: String::new(),
                    unspoken_text: String::new(),
                    preserved_history_text: "[Interrupted while thinking]".to_string(),
                    timestamp: now,
                };

                self.record_event(ConversationEvent::StateChanged {
                    from,
                    to,
                    timestamp: now,
                });
                Ok(res)
            }
            _ => Err(TransitionError::InvalidTransition {
                from: self.current_state.name(),
                to: "Interrupted",
                reason: "Can only interrupt while Speaking or Thinking".into(),
            }),
        }
    }

    /// User said a hesitation/prompt ("Aria ơi..."); reply with short ack and keep listening window open.
    pub fn await_continuation(
        &mut self,
        now: u64,
        prompt_ack: impl Into<String>,
        timeout_secs: u64,
    ) -> Result<ConversationEvent, TransitionError> {
        let ack = prompt_ack.into();
        let expires_at = now + timeout_secs;

        let from = self.current_state.name().to_string();
        self.current_state = ConversationState::AwaitingContinuation {
            started_at: now,
            prompt_ack: ack.clone(),
            expires_at,
        };
        let to = self.current_state.name().to_string();

        let event = ConversationEvent::ContinuationRequested { ack, expires_at };
        self.record_event(ConversationEvent::StateChanged {
            from,
            to,
            timestamp: now,
        });
        self.record_event(event.clone());
        Ok(event)
    }

    /// All audio has finished playback without interruption; return to Idle.
    pub fn complete_speech(&mut self, now: u64) -> Result<ConversationEvent, TransitionError> {
        match &self.current_state {
            ConversationState::Speaking {
                utterance_id,
                full_text,
                ..
            } => {
                let utt_id = utterance_id.clone();
                let full = full_text.clone();

                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Idle;
                let to = self.current_state.name().to_string();

                let event = ConversationEvent::SpeechCompleted {
                    utterance_id: utt_id,
                    full_text: full,
                    timestamp: now,
                };
                self.record_event(ConversationEvent::StateChanged {
                    from,
                    to,
                    timestamp: now,
                });
                self.record_event(event.clone());
                Ok(event)
            }
            _ => Err(TransitionError::InvalidTransition {
                from: self.current_state.name(),
                to: "Idle",
                reason: "Can only complete speech from Speaking state".into(),
            }),
        }
    }

    /// Check if awaiting continuation has expired.
    pub fn check_timeouts(&mut self, now: u64) -> Option<ConversationEvent> {
        if let ConversationState::AwaitingContinuation { expires_at, .. } = self.current_state {
            if now >= expires_at {
                let from = self.current_state.name().to_string();
                self.current_state = ConversationState::Idle;
                let to = self.current_state.name().to_string();

                let event = ConversationEvent::ContinuationExpired { timestamp: now };
                self.record_event(ConversationEvent::StateChanged {
                    from,
                    to,
                    timestamp: now,
                });
                self.record_event(event.clone());
                return Some(event);
            }
        }
        None
    }

    /// Reset state unconditionally back to Idle.
    pub fn reset(&mut self, now: u64) {
        let from = self.current_state.name().to_string();
        self.current_state = ConversationState::Idle;
        let to = self.current_state.name().to_string();
        self.record_event(ConversationEvent::StateChanged {
            from,
            to,
            timestamp: now,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_normal_conversation_turn_flow() {
        let mut fsm = ConversationStateMachine::new();
        assert_eq!(fsm.state(), &ConversationState::Idle);

        // 1. User speaks
        let interrupt = fsm.on_user_speech_started(1000).expect("start listening");
        assert!(interrupt.is_none());
        assert!(fsm.state().is_listening());

        // 2. Transcript final
        let think_ev = fsm
            .on_transcript_final(1002, "Chào bạn")
            .expect("start thinking");
        assert!(fsm.state().is_thinking());
        assert_eq!(
            think_ev,
            ConversationEvent::ThinkingStarted {
                user_input: "Chào bạn".into(),
                timestamp: 1002,
            }
        );

        // 3. Audio ready -> Speaking
        let speak_ev = fsm
            .on_first_audio_ready(1003, "utt-1", "Chào bạn, tôi là Aria.")
            .expect("start speaking");
        assert!(fsm.state().is_speaking());
        assert_eq!(
            speak_ev,
            ConversationEvent::SpeakingStarted {
                utterance_id: "utt-1".into(),
                text: "Chào bạn, tôi là Aria.".into(),
                timestamp: 1003,
            }
        );

        // 4. Audio completes -> Idle
        let comp_ev = fsm.complete_speech(1006).expect("complete speech");
        assert!(fsm.state().is_idle());
        assert_eq!(
            comp_ev,
            ConversationEvent::SpeechCompleted {
                utterance_id: "utt-1".into(),
                full_text: "Chào bạn, tôi là Aria.".into(),
                timestamp: 1006,
            }
        );
    }

    #[test]
    fn test_barge_in_interruption_preserves_heard_text() {
        let mut fsm = ConversationStateMachine::new();

        // Put in Speaking state
        fsm.on_user_speech_started(1000).unwrap();
        fsm.on_transcript_final(1001, "Kể chuyện đi").unwrap();
        fsm.on_first_audio_ready(
            1002,
            "utt-2",
            "Ngày xửa ngày xưa, ở một ngôi làng nhỏ có một nàng tiên",
        )
        .unwrap();

        // Audio progress: user heard "Ngày xửa ngày xưa"
        fsm.update_heard_progress("Ngày xửa ngày xưa");

        // User speaks over character
        let interrupt_res = fsm
            .on_user_speech_started(1004)
            .expect("user speech triggers interrupt");
        let res = interrupt_res.expect("Must have interruption result");

        assert_eq!(res.heard_text, "Ngày xửa ngày xưa");
        assert!(res.unspoken_text.contains("ngôi làng nhỏ"));
        assert_eq!(
            res.preserved_history_text,
            "Ngày xửa ngày xưa [Interrupted by user]"
        );

        // Current state moved to Listening for the new utterance!
        assert!(fsm.state().is_listening());
    }

    #[test]
    fn test_awaiting_continuation_and_timeout() {
        let mut fsm = ConversationStateMachine::new();

        // User says "Aria ơi..." -> Prompt ack "Dạ?" with 4s timeout
        fsm.await_continuation(1000, "Dạ?", 4)
            .expect("await continuation");
        assert!(matches!(
            fsm.state(),
            ConversationState::AwaitingContinuation { .. }
        ));

        // At 1002 (not expired yet)
        assert!(fsm.check_timeouts(1002).is_none());
        assert!(matches!(
            fsm.state(),
            ConversationState::AwaitingContinuation { .. }
        ));

        // At 1004 (expired)
        let ev = fsm.check_timeouts(1004).expect("timeout expired");
        assert_eq!(
            ev,
            ConversationEvent::ContinuationExpired { timestamp: 1004 }
        );
        assert!(fsm.state().is_idle());
    }
}
