//! Autonomous Life Foundation (P0-E).
//!
//! Separates:
//! 1. Subconscious Reflex (0 LLM, 0 GPU, ultra-low CPU): procedural blinking, breathing rate,
//!    and natural idle gaze tracking with deadzone and ignore probabilities.
//! 2. Conscious Thinking: Deliberate checks governed by cooldowns, user focus status,
//!    boredom/curiosity thresholds, and anti-loop guards before proposing autonomous speech turns.

use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

/// Configuration for the autonomous life cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutonomousLifeConfig {
    /// Heartbeat tick interval in milliseconds (default: 2500ms).
    pub heartbeat_interval_ms: u64,

    /// Minimum enforced cooldown between autonomous speech outbursts in seconds (default: 45s).
    pub min_speech_cooldown_secs: u64,

    /// Boredom / curiosity score threshold required to trigger deliberate thinking (default: 0.70).
    pub boredom_threshold: f32,

    /// Anti-loop sliding window duration in seconds (default: 900s = 15 minutes).
    pub anti_loop_window_secs: u64,

    /// Minimum duration between procedural blinks in seconds (default: 3.0s).
    pub blink_min_interval_secs: f32,

    /// Maximum duration between procedural blinks in seconds (default: 5.5s).
    pub blink_max_interval_secs: f32,

    /// Gaze deadzone in normalized coordinates (default: 0.08) to prevent micro-jitter.
    pub gaze_deadzone: f32,

    /// Probability [0.0, 1.0] of intentionally ignoring mouse movement (default: 0.35).
    pub gaze_ignore_chance: f32,
}

impl Default for AutonomousLifeConfig {
    fn default() -> Self {
        Self {
            heartbeat_interval_ms: 2500,
            min_speech_cooldown_secs: 45,
            boredom_threshold: 0.70,
            anti_loop_window_secs: 900,
            blink_min_interval_secs: 3.0,
            blink_max_interval_secs: 5.5,
            gaze_deadzone: 0.08,
            gaze_ignore_chance: 0.35,
        }
    }
}

/// Output of procedural subconscious reflexes (0 LLM tokens, 0 GPU VRAM).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubconsciousReflexOutput {
    /// Whether an auto-blink animation should be triggered.
    pub should_blink: bool,

    /// Optional normalized gaze direction [-1.0, 1.0] for avatar head/eyes.
    pub gaze_target: Option<(f32, f32)>,

    /// Breathing frequency multiplier (1.0 = normal, 1.4 = excited).
    pub breathing_rate: f32,

    /// Subtle procedural posture sway delta.
    pub posture_sway: f32,
}

/// Reflex actions dispatched to the frontend HUD or avatar controller.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SubconsciousReflexAction {
    Blink,
    LookAt { x: f32, y: f32 },
    AdjustBreathing { rate: f32 },
}

/// Classification of autonomous actions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AutonomousActionType {
    SpontaneousBanter,
    CuriosityObservation,
    MemoryRecallQuestion,
}

/// Proposal for conscious action generated by the autonomous scheduler.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AutonomousProposal {
    pub action_type: AutonomousActionType,
    pub topic: String,
    pub reason: String,
    pub salience_score: f32,
    pub proposed_at: u64,
}

/// State tracking for procedural reflex generator.
#[derive(Debug)]
struct SubconsciousState {
    last_blink_at_secs: f64,
    next_blink_interval_secs: f64,
    current_gaze: (f32, f32),
    pseudo_rng_seed: u64,
}

impl SubconsciousState {
    fn new() -> Self {
        Self {
            last_blink_at_secs: 0.0,
            next_blink_interval_secs: 3.5,
            current_gaze: (0.0, 0.0),
            pseudo_rng_seed: 123456789,
        }
    }

    /// Fast LCG pseudo-random float [0.0, 1.0) without external dependencies.
    fn next_rand(&mut self) -> f32 {
        self.pseudo_rng_seed = self
            .pseudo_rng_seed
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1);
        let val = (self.pseudo_rng_seed >> 33) as u32;
        val as f32 / 2147483648.0
    }
}

/// History record for anti-loop checking.
#[derive(Debug, Clone)]
struct SpokenTopicRecord {
    topic: String,
    spoken_at_secs: u64,
}

/// Core Autonomous Life Engine orchestrating circadian ticks.
#[derive(Debug)]
pub struct AutonomousLifeEngine {
    config: AutonomousLifeConfig,
    reflex_state: SubconsciousState,
    last_autonomous_speech_at: u64,
    topic_history: VecDeque<SpokenTopicRecord>,
    shutdown_requested: Arc<AtomicBool>,
}

impl Default for AutonomousLifeEngine {
    fn default() -> Self {
        Self::new(AutonomousLifeConfig::default())
    }
}

impl AutonomousLifeEngine {
    pub fn new(config: AutonomousLifeConfig) -> Self {
        Self {
            config,
            reflex_state: SubconsciousState::new(),
            last_autonomous_speech_at: 0,
            topic_history: VecDeque::new(),
            shutdown_requested: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Access shutdown flag for graceful termination of long-running loops.
    pub fn shutdown_flag(&self) -> Arc<AtomicBool> {
        self.shutdown_requested.clone()
    }

    /// Signal shutdown.
    pub fn request_shutdown(&self) {
        self.shutdown_requested.store(true, Ordering::SeqCst);
    }

    pub fn is_shutdown(&self) -> bool {
        self.shutdown_requested.load(Ordering::SeqCst)
    }

    /// Execute the Subconscious Reflex Tick (0 LLM, 0 GPU, sub-microsecond CPU).
    pub fn tick_subconscious_reflex(
        &mut self,
        now_secs: f64,
        mouse_coord: Option<(i32, i32)>,
        screen_dim: Option<(u32, u32)>,
        arousal: f32,
    ) -> SubconsciousReflexOutput {
        // 1. Procedural Blinking
        let elapsed_blink = now_secs - self.reflex_state.last_blink_at_secs;
        let should_blink = if elapsed_blink >= self.reflex_state.next_blink_interval_secs {
            self.reflex_state.last_blink_at_secs = now_secs;
            let range = self.config.blink_max_interval_secs - self.config.blink_min_interval_secs;
            self.reflex_state.next_blink_interval_secs = (self.config.blink_min_interval_secs
                + self.reflex_state.next_rand() * range)
                as f64;
            true
        } else {
            false
        };

        // 2. Idle Gaze / Look-at Tracking
        let mut gaze_target = None;
        if let (Some((mx, my)), Some((sw, sh))) = (mouse_coord, screen_dim) {
            if sw > 0 && sh > 0 {
                // Map to [-1.0, 1.0] center-origin
                let norm_x = ((mx as f32 / sw as f32) * 2.0 - 1.0).clamp(-1.0, 1.0);
                let norm_y = (((sh as i32 - my) as f32 / sh as f32) * 2.0 - 1.0).clamp(-1.0, 1.0);

                let dx = norm_x - self.reflex_state.current_gaze.0;
                let dy = norm_y - self.reflex_state.current_gaze.1;
                let dist = (dx * dx + dy * dy).sqrt();

                // Apply deadzone and ignore probability
                if dist >= self.config.gaze_deadzone {
                    let rand_roll = self.reflex_state.next_rand();
                    if rand_roll >= self.config.gaze_ignore_chance {
                        self.reflex_state.current_gaze = (norm_x, norm_y);
                        gaze_target = Some((norm_x, norm_y));
                    }
                }
            }
        }

        // 3. Breathing Frequency modulation
        let clamped_arousal = arousal.clamp(0.0, 1.0);
        let breathing_rate = 1.0 + 0.4 * clamped_arousal;

        // 4. Subtle Posture Sway (sine approximation using time)
        let posture_sway = ((now_secs * 0.5).sin() * 0.05) as f32;

        SubconsciousReflexOutput {
            should_blink,
            gaze_target,
            breathing_rate,
            posture_sway,
        }
    }

    /// Check whether a deliberate conscious autonomous speech proposal should be produced.
    ///
    /// Respects:
    /// - Conversation state (must be completely Idle)
    /// - Minimum speech cooldown (e.g. 45s)
    /// - User busy penalty (e.g. user writing code / playing game raises threshold)
    /// - Boredom / Curiosity threshold
    /// - Anti-loop guard (cannot repeat recent topic within 15 mins)
    pub fn evaluate_conscious_proposal(
        &mut self,
        now_secs: u64,
        is_conversation_idle: bool,
        is_user_busy: bool,
        curiosity_score: f32,
        candidate_topic: impl Into<String>,
        action_type: AutonomousActionType,
    ) -> Option<AutonomousProposal> {
        // 1. Must be completely idle
        if !is_conversation_idle {
            return None;
        }

        // 2. Cooldown check
        if now_secs.saturating_sub(self.last_autonomous_speech_at)
            < self.config.min_speech_cooldown_secs
        {
            return None;
        }

        // 3. Threshold check with busy user penalty
        let required_threshold = if is_user_busy {
            // User is busy coding or gaming: raise threshold to 0.90 to avoid annoyance
            0.90
        } else {
            self.config.boredom_threshold
        };

        if curiosity_score < required_threshold {
            return None;
        }

        // 4. Clean expired anti-loop topics
        let cutoff = now_secs.saturating_sub(self.config.anti_loop_window_secs);
        while let Some(front) = self.topic_history.front() {
            if front.spoken_at_secs < cutoff {
                self.topic_history.pop_front();
            } else {
                break;
            }
        }

        let topic = candidate_topic.into();

        // 5. Anti-loop duplication check
        let is_duplicate = self
            .topic_history
            .iter()
            .any(|r| r.topic.eq_ignore_ascii_case(&topic));
        if is_duplicate {
            return None;
        }

        // 6. Record topic and update cooldown timestamp
        self.topic_history.push_back(SpokenTopicRecord {
            topic: topic.clone(),
            spoken_at_secs: now_secs,
        });
        self.last_autonomous_speech_at = now_secs;

        Some(AutonomousProposal {
            action_type,
            topic,
            reason: format!(
                "Autonomous curiosity triggered with score {:.2}",
                curiosity_score
            ),
            salience_score: curiosity_score,
            proposed_at: now_secs,
        })
    }

    /// Reset speech cooldown and topic history.
    pub fn reset_cooldown(&mut self) {
        self.last_autonomous_speech_at = 0;
        self.topic_history.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_subconscious_reflex_0_llm_cost() {
        let mut engine = AutonomousLifeEngine::default();

        // 1. Run reflex tick at t=0
        let r1 = engine.tick_subconscious_reflex(0.0, Some((100, 100)), Some((1920, 1080)), 0.2);
        assert!(!r1.should_blink);
        assert!((r1.breathing_rate - 1.08).abs() < 0.01);

        // 2. Advance time past blink interval (e.g. 6.0s)
        let r2 = engine.tick_subconscious_reflex(6.0, Some((100, 100)), Some((1920, 1080)), 0.8);
        assert!(r2.should_blink, "Blink must trigger after elapsed interval");
        assert!((r2.breathing_rate - 1.32).abs() < 0.01);
    }

    #[test]
    fn test_conscious_proposal_enforces_cooldown_and_anti_loop() {
        let mut engine = AutonomousLifeEngine::default();

        // Turn 1 at t=100s with curiosity 0.85
        let p1 = engine.evaluate_conscious_proposal(
            100,
            true,  // is_idle
            false, // not busy
            0.85,
            "Rust Life",
            AutonomousActionType::SpontaneousBanter,
        );
        assert!(p1.is_some(), "Turn 1 must be accepted");

        // Turn 2 at t=120s (only 20s later, cooldown requires 45s)
        let p2 = engine.evaluate_conscious_proposal(
            120,
            true,
            false,
            0.95,
            "Game News",
            AutonomousActionType::SpontaneousBanter,
        );
        assert!(p2.is_none(), "Must be blocked by 45s cooldown");

        // Turn 3 at t=160s (>45s later), but trying to repeat the SAME topic "Rust Life"
        let p3 = engine.evaluate_conscious_proposal(
            160,
            true,
            false,
            0.95,
            "Rust Life",
            AutonomousActionType::SpontaneousBanter,
        );
        assert!(
            p3.is_none(),
            "Must be blocked by Anti-Loop guard within 15 mins"
        );

        // Turn 4 at t=160s with a NEW topic "Game News"
        let p4 = engine.evaluate_conscious_proposal(
            160,
            true,
            false,
            0.80,
            "Game News",
            AutonomousActionType::SpontaneousBanter,
        );
        assert!(p4.is_some(), "Different topic after cooldown must succeed");
    }

    #[test]
    fn test_busy_user_penalty_raises_threshold() {
        let mut engine = AutonomousLifeEngine::default();

        // Curiosity is 0.75 (above default 0.70), but user is busy
        let p = engine.evaluate_conscious_proposal(
            100,
            true,
            true, // user IS busy!
            0.75,
            "Random Chit Chat",
            AutonomousActionType::SpontaneousBanter,
        );
        assert!(p.is_none(), "Busy user must raise threshold to 0.90");

        // When curiosity exceeds 0.90 even if busy
        let p_urgent = engine.evaluate_conscious_proposal(
            100,
            true,
            true,
            0.92,
            "Critical Update",
            AutonomousActionType::CuriosityObservation,
        );
        assert!(
            p_urgent.is_some(),
            "Curiosity >= 0.90 overcomes busy penalty"
        );
    }
}
