use serde::{Deserialize, Serialize};

/// Provider-neutral request structure for text generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LlmRequest {
    /// Core prompt content sent to the model.
    pub prompt: String,

    /// Optional high-priority system directive for character persona.
    pub system_instruction: Option<String>,

    /// Sampling temperature (0.0 to 2.0).
    pub temperature: Option<f32>,

    /// Maximum tokens to generate.
    pub max_tokens: Option<u32>,
}

impl LlmRequest {
    /// Create a standard request with a prompt.
    pub fn new(prompt: impl Into<String>) -> Self {
        Self {
            prompt: prompt.into(),
            system_instruction: None,
            temperature: None,
            max_tokens: None,
        }
    }

    /// Create a request with both prompt and system instruction.
    pub fn with_system(prompt: impl Into<String>, system_instruction: impl Into<String>) -> Self {
        Self {
            prompt: prompt.into(),
            system_instruction: Some(system_instruction.into()),
            temperature: None,
            max_tokens: None,
        }
    }

    /// Set or update the system instruction.
    pub fn with_system_instruction(mut self, system_instruction: impl Into<String>) -> Self {
        self.system_instruction = Some(system_instruction.into());
        self
    }

    /// Set sampling temperature.
    pub fn with_temperature(mut self, temperature: f32) -> Self {
        self.temperature = Some(temperature);
        self
    }

    /// Set max output tokens limit.
    pub fn with_max_tokens(mut self, max_tokens: u32) -> Self {
        self.max_tokens = Some(max_tokens);
        self
    }
}

impl Default for LlmRequest {
    fn default() -> Self {
        Self::new("")
    }
}

/// Token usage statistics returned by the LLM provider.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct LlmUsage {
    pub prompt_tokens: Option<u32>,
    pub completion_tokens: Option<u32>,
    pub total_tokens: Option<u32>,
}

impl LlmUsage {
    pub fn new(prompt_tokens: u32, completion_tokens: u32) -> Self {
        Self {
            prompt_tokens: Some(prompt_tokens),
            completion_tokens: Some(completion_tokens),
            total_tokens: Some(prompt_tokens + completion_tokens),
        }
    }
}

/// Provider-neutral response structure.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LlmResponse {
    /// Text generated by the model.
    pub text: String,

    /// Optional token consumption metadata.
    pub usage: Option<LlmUsage>,

    /// Model finish reason (e.g., "STOP", "MAX_TOKENS", "SAFETY").
    pub finish_reason: Option<String>,
}

impl LlmResponse {
    pub fn new(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            usage: None,
            finish_reason: None,
        }
    }

    pub fn with_usage(text: impl Into<String>, usage: LlmUsage) -> Self {
        Self {
            text: text.into(),
            usage: Some(usage),
            finish_reason: None,
        }
    }

    pub fn with_finish_reason(mut self, reason: impl Into<String>) -> Self {
        self.finish_reason = Some(reason.into());
        self
    }
}

/// Domain error variants for LLM provider operations.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, thiserror::Error)]
pub enum LlmError {
    #[error("Rate limited by provider: {message}. Retry after {retry_after_secs:?} seconds")]
    RateLimited {
        message: String,
        retry_after_secs: Option<u64>,
    },

    #[error("Authentication failed (invalid API key or permissions): {0}")]
    AuthenticationFailed(String),

    #[error("Invalid request parameters: {0}")]
    InvalidRequest(String),

    #[error("Network connection failure: {0}")]
    NetworkError(String),

    #[error("Provider call timed out: {0}")]
    Timeout(String),

    #[error("Model service unavailable or overloaded: {0}")]
    ModelUnavailable(String),

    #[error("Provider error: {0}")]
    Other(String),
}

impl From<LlmError> for vc_core::CoreError {
    fn from(err: LlmError) -> Self {
        vc_core::CoreError::ProviderError(err.to_string())
    }
}

/// The generic LLM provider abstraction (Skill 20: LLM Provider Engineering).
pub trait LlmProvider: Send + Sync {
    /// Generate a text response synchronously from an `LlmRequest`.
    fn generate_text(&self, request: LlmRequest) -> vc_core::Result<LlmResponse>;

    /// Human-readable provider identifier.
    fn name(&self) -> &'static str {
        "GenericLlmProvider"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llm_request_builder() {
        let req = LlmRequest::new("Hello")
            .with_temperature(0.7)
            .with_max_tokens(1024);

        assert_eq!(req.prompt, "Hello");
        assert_eq!(req.system_instruction, None);
        assert_eq!(req.temperature, Some(0.7));
        assert_eq!(req.max_tokens, Some(1024));
    }

    #[test]
    fn test_llm_response_and_usage() {
        let usage = LlmUsage::new(50, 20);
        assert_eq!(usage.total_tokens, Some(70));

        let res = LlmResponse::with_usage("Generated reply", usage)
            .with_finish_reason("STOP");

        assert_eq!(res.text, "Generated reply");
        assert_eq!(res.usage, Some(usage));
        assert_eq!(res.finish_reason.as_deref(), Some("STOP"));
    }

    #[test]
    fn test_llm_error_conversion_to_core_error() {
        let err = LlmError::RateLimited {
            message: "Too many requests".into(),
            retry_after_secs: Some(10),
        };
        let core_err: vc_core::CoreError = err.into();
        assert!(matches!(core_err, vc_core::CoreError::ProviderError(_)));
        assert!(core_err.to_string().contains("Rate limited"));
    }
}
